### ISSUE TITLE
Utils module imported in test code

### ISSUE THREAD

**Issue by Kalana304** [RuochenFan/S4Net#4]
Hi, I have installed the utils package using pip and tried to import cython and other modules but no luck. Is this a seperate script or can you tell me what module needs to be installed?

**Comment by aviaisr** [comment]
Hi,
Have you solved this problem?
I'm getting a similar issue:

Traceback (most recent call last):
  File "C:/CP/DL_REPOSITORIES/S4Net/experiment/test_seg.py", line 21, in <module>
    import network_desp
  File "C:\CP\DL_REPOSITORIES\S4Net\experiment\network_desp.py", line 14, in <module>
    from anchor_target_layer import anchor_target_layer
  File "C:\CP\DL_REPOSITORIES\S4Net\experiment\anchor_target_layer.py", line 15, in <module>
    from utils.cython_bbox import bbox_overlaps
ModuleNotFoundError: No module named 'utils.cython_bbox'

**Comment by ghost** [comment]
I am facing the exact same issue. Let me know what solution worked for you

**Comment by Patrickctyyx** [comment]
I just met the same problem, and here is my solution:

1. If the Python version is 3.4~3.6 and the OS is Linux, then the code should work without error
2. If error occurred, then
	1. `cd lib`
	2. `pip install .`
	3. find installed package in `site-packages`, for me is `/home/sse/anaconda3/envs/SODKeras/lib/python3.6/site-packages/utils` , then copy the `*.so` files to 'lib/utils'
	4. Then the code should work properly
